// const ADD_USER = 'CREATE_USER';
// const DELETE_USER = 'DELETE_USER';
const SET_LOADING = 'SET_LOADING';
const SET_ONE_USER = 'SET_ONE_USER';
const SET_USERS = 'SET_USERS';
// const UPDATE_USER = 'UPDATE_USER';


export {
  // ADD_USER,
  // DELETE_USER,
  SET_LOADING,
  SET_ONE_USER,
  SET_USERS,
  // UPDATE_USER
};
